version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: app_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    networks:
      - app_network
  
  app-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - app_network

networks:
  app_network:
    name: app_network
    driver: bridge 
