version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: app_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    networks:
      - app_network

networks:
  app_network:
    name: app_network
    driver: bridge 