name: Deploy Client
on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - '.github/workflows/client.yml'

permissions:
  actions: read
  contents: read

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 #v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4
      - uses: Genez-io/genezio-github-action@31bfaba1b4fd704797f214ef0c66cd6b3f65d43b # v3
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: Deploy client
        working-directory: ./client
        run: genezio deploy
