name: Criticality Score Analysis

on:
  push:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install criticality_score
        run: go install github.com/ossf/criticality_score/v2/cmd/criticality_score@latest

      - name: Run criticality_score
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run criticality_score on this repository
          criticality_score -depsdev-disable "https://github.com/FirstForce/SS" 