name: OpenSSF Scorecard Analysis

on:
  push:
  workflow_dispatch:

jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run Scorecard using Docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run scorecard in Docker on the current repository and output to console
          docker run --rm \
            -e GITHUB_AUTH_TOKEN=$GITHUB_TOKEN \
            gcr.io/openssf/scorecard:latest \
            --repo=https://github.com/${{ github.repository }} \
            --format=json | tee scorecard-results.json
          
          # Display a more human-readable summary
          echo "============= SCORECARD RESULTS SUMMARY ============="
          cat scorecard-results.json | jq -r '.checks[] | "Check: \(.name), Score: \(.score), Details: \(.reason)"' 