name: OpenSSF Scorecard Analysis

on:
  push:
  workflow_dispatch:

jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Scorecard
        run: go install github.com/ossf/scorecard/v4/cmd/scorecard@latest

      - name: Run Scorecard analysis
        run: |
          # Run scorecard on the current repository and output to console
          scorecard --repo=https://github.com/${{ github.repository }} --format=json | tee scorecard-results.json
          # Display a more human-readable summary
          echo "============= SCORECARD RESULTS SUMMARY ============="
          cat scorecard-results.json | jq -r '.checks[] | "Check: \(.name), Score: \(.score), Details: \(.reason)"' 