name: Deploy to Docker Swarm

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - 'docker-compose.yml'
      - 'broker/mosquitto.conf'
      - '.github/workflows/swarm.yml'

jobs:
  tests:
    uses: FirstForce/SS/.github/workflows/tests.yml@4f94105d0f482895fc049a024708e2d7cade1baf

  deploy:
    needs: tests
    if: ${{ !failure() && !cancelled() }}
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: stefandarius/mqtt-ss-api

    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

    - name: Log in to Docker Hub
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE_NAME:${{ steps.vars.outputs.sha_short }} ./server
        docker push $IMAGE_NAME:${{ steps.vars.outputs.sha_short }}

    - name: Generate updated Compose file
      run: |
        sed "s|$IMAGE_NAME:.*|$IMAGE_NAME:${{ steps.vars.outputs.sha_short }}|" docker-compose.yml > docker-compose.deploy.yml

    - name: Copy Compose file to remote server
      uses: appleboy/scp-action@6d1fc191a822daa12faa45f3a985413f995ff5c5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "docker-compose.deploy.yml"
        target: "/home/${{ secrets.SSH_USER }}/mystack/"

    - name: Copy Mosquitto Config file to remote server
      uses: appleboy/scp-action@6d1fc191a822daa12faa45f3a985413f995ff5c5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "./broker/mosquitto.conf"
        target: "/home/${{ secrets.SSH_USER }}/mystack/"

    - name: Deploy updated stack on remote server
      uses: appleboy/ssh-action@55dabf81b49d4120609345970c91507e2d734799
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull stefandarius/mqtt-ss-api:${{ steps.vars.outputs.sha_short }}
          docker stack deploy -c /home/${{ secrets.SSH_USER }}/mystack/docker-compose.deploy.yml mystack
