name: Deploy to Docker Swarm

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - 'docker-compose.yml'
      - 'broker/mosquitto.conf'
      - '.github/workflows/swarm.yml'

permissions:
  actions: read

jobs:
  tests:
    uses: FirstForce/SS/.github/workflows/tests.yml@542058201257a0367fdc5025fda52b2e7b30acea

  deploy:
    needs: tests
    if: ${{ !failure() && !cancelled() }}
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: stefandarius/mqtt-ss-api

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

    - name: Log in to Docker Hub
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE_NAME:${{ steps.vars.outputs.sha_short }} ./server
        docker push $IMAGE_NAME:${{ steps.vars.outputs.sha_short }}

    - name: Generate updated Compose file
      run: |
        sed "s|$IMAGE_NAME:.*|$IMAGE_NAME:${{ steps.vars.outputs.sha_short }}|" docker-compose.yml > docker-compose.deploy.yml

    - name: Copy Compose file to remote server
      uses: appleboy/scp-action@7f18bf0ec86d81d9fba5e2bdf3253b7b22a604ab
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "docker-compose.deploy.yml"
        target: "/home/${{ secrets.SSH_USER }}/mystack/"

    - name: Copy Mosquitto Config file to remote server
      uses: appleboy/scp-action@7f18bf0ec86d81d9fba5e2bdf3253b7b22a604ab
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "./broker/mosquitto.conf"
        target: "/home/${{ secrets.SSH_USER }}/mystack/"

    - name: Deploy updated stack on remote server
      uses: appleboy/ssh-action@ffd1eec36471c1bfbebcf1941411db862c9b0e38
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull stefandarius/mqtt-ss-api:${{ steps.vars.outputs.sha_short }}
          docker stack deploy -c /home/${{ secrets.SSH_USER }}/mystack/docker-compose.deploy.yml mystack
