name: Test Go Routes

on:
  pull_request:
    paths:
      - 'server/**'
      - '.github/workflows/tests.yml'
  workflow_call:

permissions:
  actions: read

jobs:
  test-routes:
    name: Run tests for ./server/routes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: '1.24' # Update as needed

      - name: Run tests with coverage
        run: |
          cd server/routes
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out | tee coverage.txt
          coverage=$(go tool cover -func=coverage.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total coverage: $coverage%"
          coverage_int=${coverage%.*}
          if [ "$coverage_int" -lt 30 ]; then
            echo "Coverage below threshold (30%)"
            exit 1
          fi
