name: Test Go Routes

on:
  pull_request:
    paths:
      - 'server/**'
      - '.github/workflows/tests.yml'
  workflow_call:

permissions:
  actions: read

jobs:
  test-routes:
    name: Run tests for ./server/routes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Set up Go
        uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639
        with:
          go-version: '1.24' # Update as needed

      - name: Run tests with coverage
        run: |
          cd server/routes
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out | tee coverage.txt
          coverage=$(go tool cover -func=coverage.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total coverage: $coverage%"
          coverage_int=${coverage%.*}
          if [ "$coverage_int" -lt 30 ]; then
            echo "Coverage below threshold (30%)"
            exit 1
          fi
